### ISSUE TITLE
How can I use turtle?

### ISSUE THREAD

**Issue by nkm96** [zazuko/rdfjs-elements#108]
Hi. I can only sink  jsonld.
I dont know how should initialize my object to put it in editor. (Im just started and not expert) 
Can you give me a simple example about turtle object?

**Comment by cristianvasquez** [comment]
Hi @nkm96,

an example:

```turtle
@base <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rel: <http://www.perceive.net/schemas/relationship/> .

<#green-goblin>
    rel:enemyOf <#spiderman> ;
    a foaf:Person ;    # in the context of the Marvel universe
    foaf:name "Green Goblin" .

<#spiderman>
    rel:enemyOf <#green-goblin> ;
    a foaf:Person ;
    foaf:name "Spiderman", "Человек-паук"@ru .
```

Some resources that could be useful:

The syntax of Turtle:
https://www.w3.org/TR/2014/REC-turtle-20140225/

The video of an online course: 
https://open.hpi.de/courses/semanticweb2016/items/3h7kCHTTxYDQdqrjN5EEkV

**Comment by nkm96** [comment]
@cristianvasquez 
thanks for your answer. I familiar with turtle object, but I dont know how should pass it into rdf-editor.
for example you initialize editor like this: 
`const initialValue = JSON.stringify(jsonld, null, 2)
const template = html`<rdf-editor format="application/ld+json" .value="${initialValue}"></rdf-editor>``
how can I do it for turtle object?

**Comment by tpluscode** [comment]
If string works for you, you can replace json with a turtle.

See it in action here: https://studio.webcomponents.dev/edit/AqJKehQIzgLrPlNJDC1b

If you want to update using quads then set the `.quads` property instead. It takes and array or RDF/JS `Quad` objects
