### ISSUE TITLE
[editor] Module parse failed error

### ISSUE THREAD

**Issue by zollillo** [zazuko/rdfjs-elements#19]
There seems to be a syntax error/typo that leeds to a failing import of `rdf-editor`.

I tried to `import '@rdfjs-elements/rdf-editor'` as it is desribed in the `README` but got an error (see attached screenshot below) that pointed to the following line of code:

https://github.com/zazuko/rdfjs-elements/blob/d72708215c97ff263edb19a3c690961c8ddbfeec/packages/rdf-editor/src/RdfEditor.js#L135

Removing the `?` solved the issue.

Screenshot of error message in console:
<img width="1305" alt="rdf-editor--module-parse-failed-error" src="https://user-images.githubusercontent.com/8833904/97018750-cd8b7300-154f-11eb-9852-28bc2d90ff51.png">

**Comment by tpluscode** [comment]
Hi @zollillo. Thank you for raising this.

The `?.` syntax for [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which is not yet fully supported on all platforms.

I can push a new version with this part removed but please tell me about your setup. Are you using a bundler?

**Comment by zollillo** [comment]
Hi @tpluscode, thank you for clarifying - I didn't know about _optional chaining_.

Yes, we are using Webpack as a module bundler.

**Comment by tpluscode** [comment]
Please try v0.3.4

**Comment by zollillo** [comment]
Hey @tpluscode, v0.3.4 is working - no errors when importing `@rdfjs-elements/rdf-editor`! Thank you for pushing a new version!

FWIW, we are using `webpack v4.42.1` and also `typescript v3.5.3`.

We tested using _optional chaining_ from within our codebase and there were no problems. 

Again, thank you! ✨

**Comment by tpluscode** [comment]
You're welcome.

TypeScript would compile down to remove this syntax. `node_modules`, however, are usually excluded from processing unless explicitly configured.

It is ironic that webpack would fail to parse this, while the syntax is otherwise [widely supported by latest browsers](https://caniuse.com/?search=optional%20chaining) :)
