### ISSUE TITLE
[bug] RO .value property is not working in SparqlEditor

### ISSUE THREAD

**Issue by osioalberto** [zazuko/rdfjs-elements#43]
The readonly `.value` property exposed by the `Editor` class from `editor-base` is shadowed in `SparqlEditor` by a local .value property (declared [here](https://github.com/zazuko/rdfjs-elements/blob/master/packages/sparql-editor/src/SparqlEditor.js#L44)). When reading the value, the parser keeps obtaining the initial value, regardless of the actions performed in the editor (namely, this happens [here](https://github.com/zazuko/rdfjs-elements/blob/master/packages/sparql-editor/src/SparqlEditor.js#L84)).

**Comment by tpluscode** [comment]
Hi @osioalberto. Thank's for reporting. Very good catch!

I had already planned a little refactoring of the `.value` property for the `rdf-editor` element. This is the perfect opportunity :). Will release an update soon
