### ISSUE TITLE
Putting ES primitives in literalHash breaks RDF/XML scriber

### ISSUE THREAD

**Issue by blake-regalia** [zazuko/rdfjs-elements#87]
Numbers seem to be crashing the converter when using RDF/XML as output: https://s.zazuko.com/2uNYvG

Since that is a graphy Scriber, the data needs to be in concise hash strict mode (c3r/c4r) which I see is being used in other parts of this source file already. I think line 191 can just be changed to:

```js
if(term.datatype && !strict) {
```

to fix it.

https://github.com/zazuko/rdfjs-elements/blob/644b94541392b4a916329a28f4bb8a755cd39e8a/packages/formats/serializers/TransformToConciseHash.js#L118-L149

**Comment by tpluscode** [comment]
Thank your for reporting. Your suggested fix does the trick.

Fixed in `v0.4.3`. I'll update the converter in a moment too
