### ISSUE TITLE
How can I serialize n-triples?

### ISSUE THREAD

**Issue by Sozialarchiv** [zazuko/rdfjs-elements#92]
I can only find sink functions for turtle, rdfXml, trig and jsonld.

**Comment by tpluscode** [comment]
n-triples would use the `@rdfjs/serializer-ntriples`

It is not exported as a sink but only available from the sink map. Off the. top of my head, this could be like

```js
import { serializers } from '@rdfjs-elements/format-pretty'
import { toStream } from 'rdf-dataset-ext'
import getStream from 'get-stream'

// RDF/JS dataset
let dataset

const ntripleStream = serialisers.import('text/n-triples', toStream(dataset))
const triples = await getStream(ntripleStream)
```

**Comment by Sozialarchiv** [comment]
Thank you very much for this fast and helpful answer. 

Some things I had to change:

toStream(dataset) -> Readable.from(data)
text/n-triples ->  application/n-triples
format-pretty -> formats-pretty

```javascript
import { serializers } from '@rdfjs-elements/formats-pretty'
import { Readable } from 'stream'
import getStream from 'get-stream'

// RDF/JS dataset
let dataset

const ntripleStream = serialisers.import('application/n-triples', Readable.from(dataset))
const triples = await getStream(ntripleStream)
```

**Comment by Sozialarchiv** [comment]
Is there a way to add prefixes with sink map? E.g. for n3.

**Comment by Sozialarchiv** [comment]
I solved it:

```javascript
const ntripleStream = serialisers.import('application/n-triples', Readable.from(dataset), {prefixes: ...})
```

**Comment by ktk** [comment]
@Sozialarchiv would you mind proposing an extension of the readme?
